"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Data = { company: { name: string }; summary: { _count: number; _avg: { baseSalary: number | null; bonus: number | null; stock: number | null; totalComp: number | null }; _min: { totalComp: number | null }; _max: { totalComp: number | null } }; byLevel: { level: string; _count: number; _avg: { baseSalary: number | null; bonus: number | null; stock: number | null; totalComp: number | null } }[]; records: { id: string; role: string; level: string; location: string; baseSalary: number; bonus: number; stock: number; totalComp: number }[] };
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0, notation: "compact" }).format(n);
export default function CompanyPage({ params }: { params: Promise<{ normalizedName: string }> }) { const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
 useEffect(() => { params.then(({ normalizedName }) => fetch(`/api/companies/${normalizedName}`).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error); return body; }).then((body) => setData(body.data)).catch((e) => setError(e.message))); }, [params]);
 if (error) return <main className="mx-auto max-w-6xl px-5 py-12"><h1 className="text-3xl font-black">Company unavailable</h1><p className="mt-3 text-gray-600">{error}</p><Link className="mt-5 inline-block font-bold underline" href="/companies">Browse companies</Link></main>;
 if (!data) return <main className="mx-auto max-w-6xl px-5 py-12 text-gray-600">Loading company intelligence…</main>;
 const average = data.summary._avg; const total = average.totalComp ?? 0; const mix = [{ label: "Base", value: average.baseSalary ?? 0, color: "bg-[#3d7056]" }, { label: "Bonus", value: average.bonus ?? 0, color: "bg-[#8fcf9d]" }, { label: "Equity", value: average.stock ?? 0, color: "bg-[#d9ff76]" }]; const maxLevel = Math.max(...data.byLevel.map((item) => item._avg.totalComp ?? 0), 1);
 return <main className="mx-auto max-w-6xl px-5 py-12"><Link href="/companies" className="text-sm font-bold underline">← All companies</Link><section className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-moss">Company intelligence</p><h1 className="mt-2 text-4xl font-black">{data.company.name}</h1><p className="mt-2 text-gray-600">Based on {data.summary._count} submitted compensation record{data.summary._count === 1 ? "" : "s"}.</p></div><Link href="/compare" className="button">Compare offers</Link></section>
 <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="text-sm text-gray-500">Average total compensation</p><p className="mt-2 text-3xl font-black text-moss">{money(total)}</p></div><div className="card p-5"><p className="text-sm text-gray-500">Observed range</p><p className="mt-2 text-2xl font-black">{money(data.summary._min.totalComp ?? 0)} – {money(data.summary._max.totalComp ?? 0)}</p></div><div className="card p-5"><p className="text-sm text-gray-500">Levels represented</p><p className="mt-2 text-3xl font-black">{data.byLevel.length}</p></div></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card p-6"><h2 className="text-xl font-black">Average pay mix</h2><p className="mt-1 text-sm text-gray-600">How the average package is structured.</p><div className="mt-6 flex h-9 overflow-hidden rounded-lg">{mix.map((part) => <div key={part.label} className={part.color} style={{ width: `${total ? (part.value / total) * 100 : 0}%` }} title={`${part.label}: ${money(part.value)}`} />)}</div><div className="mt-5 space-y-3">{mix.map((part) => <div key={part.label} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2"><i className={`h-3 w-3 rounded-sm ${part.color}`} />{part.label}</span><b>{money(part.value)} · {total ? Math.round((part.value / total) * 100) : 0}%</b></div>)}</div></div>
 <div className="card p-6"><h2 className="text-xl font-black">Average total pay by level</h2><p className="mt-1 text-sm text-gray-600">Level-first comparison, not title-first.</p><div className="mt-6 space-y-5">{data.byLevel.map((item) => <div key={item.level}><div className="mb-1 flex justify-between text-sm"><span className="font-bold">{item.level} <span className="font-normal text-gray-500">({item._count})</span></span><span>{money(item._avg.totalComp ?? 0)}</span></div><div className="h-3 rounded-full bg-[#e8efe8]"><div className="h-3 rounded-full bg-moss" style={{ width: `${((item._avg.totalComp ?? 0) / maxLevel) * 100}%` }} /></div></div>)}</div></div></section>
 <section className="card mt-6 overflow-x-auto"><div className="border-b p-6"><h2 className="text-xl font-black">Submitted compensation</h2><p className="mt-1 text-sm text-gray-600">Top 20 records by annual total compensation.</p></div><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b bg-[#f4f8f3] text-xs uppercase tracking-wide text-[#597060]"><tr><th className="p-4">Role</th><th>Level</th><th>Location</th><th>Base</th><th>Bonus</th><th>Equity</th><th>Total</th></tr></thead><tbody>{data.records.map((record) => <tr key={record.id} className="border-b last:border-0"><td className="p-4 font-bold">{record.role}</td><td>{record.level}</td><td>{record.location}</td><td>{money(record.baseSalary)}</td><td>{money(record.bonus)}</td><td>{money(record.stock)}</td><td className="font-bold text-moss">{money(record.totalComp)}</td></tr>)}</tbody></table></section></main>; }
