"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Row = { id: string; company: { name: string; normalizedName: string }; role: string; level: string; location: string; baseSalary: number; bonus: number; stock: number; totalComp: number };
type Meta = { page: number; pages: number; total: number };
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0, notation: "compact" }).format(n);
export function SalaryTable() { const [rows, setRows] = useState<Row[]>([]); const [meta, setMeta] = useState<Meta>({ page: 1, pages: 1, total: 0 }); const [loading, setLoading] = useState(true); const [q, setQ] = useState(""); const [level, setLevel] = useState(""); const [location, setLocation] = useState(""); const [sort, setSort] = useState("totalComp"); const [page, setPage] = useState(1);
 useEffect(() => { const timer = setTimeout(() => setPage(1), 250); return () => clearTimeout(timer); }, [q, level, location, sort]);
 useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams({ sort, page: String(page) }); if (q) params.set("q", q); if (level) params.set("level", level); if (location) params.set("location", location); setLoading(true); fetch(`/api/compensation?${params}`, { signal: controller.signal }).then((r) => r.json()).then((d) => { setRows(d.data ?? []); setMeta(d.meta ?? { page: 1, pages: 1, total: 0 }); }).catch((error) => { if (error.name !== "AbortError") setRows([]); }).finally(() => setLoading(false)); return () => controller.abort(); }, [q, level, location, sort, page]);
 return <section><div className="card mb-5 grid gap-3 p-4 md:grid-cols-4"><input aria-label="Search" placeholder="Company or role" value={q} onChange={(e) => setQ(e.target.value)} /><select value={level} onChange={(e) => setLevel(e.target.value)}><option value="">All levels</option><option>Entry</option><option>Mid</option><option>Senior</option><option>Staff</option><option>Principal</option></select><input aria-label="Location" placeholder="Location" value={location} onChange={(e) => setLocation(e.target.value)} /><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="totalComp">Highest total pay</option><option value="baseSalary">Highest base pay</option><option value="recent">Most recent</option></select></div>
 <div className="card overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-[#f4f8f3] text-xs uppercase tracking-wide text-[#597060]"><tr><th className="p-4">Company / role</th><th>Level</th><th>Location</th><th>Base</th><th>Bonus</th><th>Equity</th><th>Total pay</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-8 text-center text-gray-500">Loading live compensation data…</td></tr> : rows.length === 0 ? <tr><td colSpan={8} className="p-8 text-center text-gray-500">No compensation matches those filters.</td></tr> : rows.map((row) => <tr key={row.id} className="border-b last:border-0 hover:bg-[#fbfdfb]"><td className="p-4"><Link className="font-bold underline" href={`/companies/${row.company.normalizedName}`}>{row.company.name}</Link><div className="text-gray-500">{row.role}</div></td><td>{row.level}</td><td>{row.location}</td><td>{money(row.baseSalary)}</td><td>{money(row.bonus)}</td><td>{money(row.stock)}</td><td className="font-bold text-moss">{money(row.totalComp)}</td><td className="pr-4"><Link className="text-sm font-bold underline" href={`/compare?ids=${row.id}`}>Compare</Link></td></tr>)}</tbody></table></div>
 <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><p className="text-gray-600">{meta.total} compensation record{meta.total === 1 ? "" : "s"} · Page {meta.page} of {meta.pages}</p><div className="flex gap-2"><button className="button button-secondary text-sm disabled:opacity-50" disabled={loading || page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="button text-sm disabled:opacity-50" disabled={loading || page >= meta.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div></div></section>; }
